### ISSUE TITLE
Missing check on python3-docker

### ISSUE THREAD

**Issue by ikkemaniac** [spantaleev/gitea-docker-ansible-deploy#2]
The book is not checking if `python3-docker` is installed, like you do here:
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/custom/matrix-base/tasks/server_base/setup_debian.yml#L35-L41

It doesn't seem to be part of 
https://github.com/geerlingguy/ansible-role-docker

I can work on fixing this, do you have suggestion how you want it fixed?

**Comment by spantaleev** [comment]
I think there was a way to enable it for that role, but I need to check

**Comment by spantaleev** [comment]
Hmm.. Looks like that role has configuration options for enabling/disabling docker-compose installation, not for `python-docker`.

Hmm.. Looks like we may need to install this ourselves then, unfortunately.

**Comment by spantaleev** [comment]
Turns out that https://github.com/geerlingguy/ansible-role-docker's README points people to installing the `docker` package via `pip` using something like:

```yaml
- hosts: all

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
```

This doesn't sound great though.. This `geerlingguy.pip` role says this:

> On RedHat/CentOS, you may need to have EPEL installed before running this role. You can use the geerlingguy.repo-epel role if you need a simple way to ensure it's installed.

So we need to include `geerlingguy.repo-epel`, etc.. The rabbit hole goes deep.

------

I've created a new [com.devture.ansible.role.docker_sdk_for_python](https://github.com/devture/com.devture.ansible.role.docker_sdk_for_python) role which installs the Docker SDK for Python on various distros using official packages (no `pip`).

**Comment by ikkemaniac** [comment]
Sounds good to me :+1:
